apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: welcome-page-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Ansible welcome operator
  displayName: Ansible Welcome Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - welcomepage
  - ansible
  links:
  - name: Welcome Page Operator
    url: https://welcome-page-operator.domain
  maintainers:
  - email: maintainer1@ansible.com
    name: maintainer1
  maturity: alpha
  provider:
    name: Ansible
    url: ansible.com
  version: 0.0.0
